# frozen_string_literal: true

source "https://rubygems.org"

group(:test) do
  gem "openhab-jrubyscripting", "= 5.0.0.rc5"
  #gem "openhab-jrubyscripting", git: "https://github.com/ccutrer/openhab-jrubyscripting", ref: "7980f01a138bc24760804c10a55aae0b07d801a9"
  gem "rspec", "~> 3.11", require: false
  gem "timecop", "~> 0.9", require: false
end

group(:rules) do
  # include any gems you reference from `gemfile` calls in your rules so that
  # they'll already be available in the rules, and won't need to be
  # re-installed on every run, slowing down spec runs considerably
  gem "activesupport", "~> 6.1", require: false
end
