# frozen_string_literal: true

source "https://rubygems.org"

group(:test) do
  gem "openhab-scripting"
  gem "rspec", "~> 3.11"
  gem "rubocop"
  gem "rubocop-openhab-scripting"
  gem "rubocop-performance"
  gem "rubocop-rspec"
  gem "timecop", "~> 0.9"
end

group(:rules) do
  # include any gems you reference from `gemfile` calls in your rules so that
  # they'll already be available in the rules, and won't need to be
  # re-installed on every run, slowing down spec runs considerably
  gem "activesupport", "~> 6.1", require: false
end
